services:
  backend:
    build: ./backend
    container_name: backend
    command: sh -c "python manage.py collectstatic --noinput"
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend
      target: frontend-dist
    container_name: frontend-dist
    ports:
      - "3000:3000"
    restart: always

