services:
  backend:
    build: ./backend
    container_name: backend
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      target: frontend-dist
    container_name: frontend-dist
    networks:
      - appnet

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - appnet
