services:
  backend:
    build: ./backend
    network_mode: "host"
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always

