services:
  backend:
    build: ./backend
    container_name: backend
    command: sh -c "python manage.py collectstatic --noinput"
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend
      target: frontend-dist
    container_name: frontend-dist
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: always
